# Generated by Django 3.2.6 on 2021-10-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('username', models.CharField(max_length=122, primary_key=True, serialize=False)),
                ('a_time', models.DateTimeField()),
            ],
        ),
    ]
